export const DEPARTURE_VISIT_SELECT =
  'RIDE_EDIT_FORM_SECTION.DEPARTURE_VISIT_SELECT';
export const ARRIVAL_VISIT_SELECT =
  'RIDE_EDIT_FORM_SECTION.ARRIVAL_VISIT_SELECT';
export const VEHICLE_TYPE_SELECT = 'RIDE_EDIT_FORM_SECTION.VEHICLE_TYPE_SELECT';
export const RIDE_TYPE_SELECT = 'RIDE_EDIT_FORM_SECTION.RIDE_TYPE_SELECT';
export const RIDE_CLASS_SELECT = 'RIDE_EDIT_FORM_SECTION.RIDE_CLASS_SELECT';
export const RIDE_OCCUPATION_SELECT =
  'RIDE_EDIT_FORM_SECTION.RIDE_OCCUPATION_SELECT';
export const DEPARTURE_DATE_PICKER =
  'RIDE_EDIT_FORM_SECTION.DEPARTURE_DATE_PICKER';
export const ARRIVAL_DATE_PICKER = 'RIDE_EDIT_FORM_SECTION.ARRIVAL_DATE_PICKER';
