import {
  PLAIN_FILTERING,
  PLAIN_GROUPS,
  PLAIN_SORTING,
} from 'travel/components/VisitsArranger';

// GROUPPING

export const KEY_GROUP_VISITS_BY = 'group';
export const GROUP_VISITS_BY = {
  LOCATIONS: 'loc',
  COUNTRIES: 'c',
  YEARS: 'yr',
  YEARS_COUNTRIES: 'yr_c',
  COUNTRIES_YEARS: 'c_yr',
  TRIPS: 't',
  TRIPS_COUNTRIES: 't_c',
};

export const PLAIN_GROUPS_MAPPING = {
  [GROUP_VISITS_BY.LOCATIONS]: PLAIN_GROUPS.LOCATIONS,
  [GROUP_VISITS_BY.COUNTRIES]: PLAIN_GROUPS.COUNTRIES,
  [GROUP_VISITS_BY.YEARS]: PLAIN_GROUPS.YEARS,
  [GROUP_VISITS_BY.TRIPS]: PLAIN_GROUPS.TRIPS,
};

// SORTING
export const KEY_SORT_VISITS_BY = 'sort';
export const SORT_VISITS_BY = {
  RATING_ALPHABET: 'r_a',
  VISITS_ALPHABET: 'v_a',
  FIRST_VISIT_ALPHABET: 'fv_a',
  LAST_VISIT_ALPHABET: 'lv_a',
  ALPHABET: 'a',
};
export const SORT_VISITS_BY_DEFAULT = SORT_VISITS_BY.ALPHABET;

export const PLAIN_SORTING_MAPPING = {
  a: PLAIN_SORTING.ALPHABET,
  r: PLAIN_SORTING.RATING,
  fv: PLAIN_SORTING.FIRST_VISIT,
  lv: PLAIN_SORTING.LAST_VISIT,
  v: PLAIN_SORTING.VISITS_COUNT,
};

// FILTERING
export const KEY_FILTER_VISITS_BY = 'filter';
export const FILTER_VISITS_BY = {
  ANY: 'a',
  FOREIGN: 'f',
  DOMESTIC: 'd',
};
export const FILTER_VISITS_BY_DEFAULT = FILTER_VISITS_BY.ANY;

export const PLAIN_FILTERING_MAPPING = {
  [FILTER_VISITS_BY.ANY]: PLAIN_FILTERING.ANY,
  [FILTER_VISITS_BY.FOREIGN]: PLAIN_FILTERING.FOREIGN,
  [FILTER_VISITS_BY.DOMESTIC]: PLAIN_FILTERING.DOMESTIC,
};
