export const KEY_SORT_VISITS_BY = 'sort';
export const SORT_VISITS_BY = {
  RATING_ALPHABET: 'r_a',
  VISITS_ALPHABET: 'v_a',
  FIRST_VISIT_ALPHABET: 'fv_a',
  LAST_VISIT_ALPHABET: 'lv_a',
  ALPHABET: 'a',
};
export const SORT_VISITS_BY_DEFAULT = SORT_VISITS_BY.ALPHABET;

export const PLAIN_SORTING = {
  ALPHABET: 'ALPHABET',
  RATING: 'RATING',
  FIRST_VISIT: 'FIRST_VISIT',
  LAST_VISIT: 'LAST_VISIT',
  VISITS_COUNT: 'VISITS_COUNT',
};

export const PLAIN_SORTING_MAPPING = {
  a: PLAIN_SORTING.ALPHABET,
  r: PLAIN_SORTING.RATING,
  fv: PLAIN_SORTING.FIRST_VISIT,
  lv: PLAIN_SORTING.LAST_VISIT,
  v: PLAIN_SORTING.VISITS_COUNT,
};
