import React from 'react';
import Typography from '@material-ui/core/Typography';
import { resolveTripCaption } from 'travel/models/trips/utils';

export default function TripEditTitle({
  isCreation,
  className,
  provision,
  formikProps: { values },
}) {
  const { trip: tripFormValues, visits: visitsFormValues } = values;
  const { countriesDict, locationsDict } = provision;

  const modeCaption = isCreation
    ? 'Создание поездки'
    : 'Редактирование поездки';

  const tripName = tripFormValues.hasAutogeneratedTripName
    ? resolveTripCaption(
        visitsFormValues,
        countriesDict,
        locationsDict[tripFormValues.originLocationId] &&
          locationsDict[tripFormValues.originLocationId].countryId,
        tripFormValues.tripName,
      )
    : tripFormValues.tripName;

  const tripCaption = `${modeCaption}: "${tripName}"`;

  return (
    <Typography variant="h6" className={className}>
      {tripCaption}
    </Typography>
  );
}
